import { useEffect, useState } from "react"
import Layout from '@/components/layout'
import Head from 'next/head'

export default function Login() {
    // const router = useRouter();
    const [text, setText] = useState('');
    const [password, setPassword] = useState('');

    function tryLogin(req, res) {
        const data = {
            userName: text,
            password: password
        }
        fetch('/api/login', {
            method: 'POST',
            body: JSON.stringify(data)
        })
            .then(response => response.json())
            .then(response => {
                if (response) {
                    // console.log(response);
                    localStorage.setItem('jwt', response);
                }
            });
    }

    return (
        <>
      <Layout>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>

        <div className="bg-slate-800">
            <form className="flex items-center justify-center">
                <span>아이디</span>
                <input type='text' value={text} onChange={(e) => setText(e.target.value)}></input> <br />
                <span>비밀번호</span>
                <input type='password' value={password} onChange={(e) => setPassword(e.target.value)}></input>
                <br />
                <button onClick={tryLogin}>로그인</button>
            </form>
        </div>


      </Layout>
    </>
        
    )
}


