import { useEffect, useState } from "react"
import Layout from '@/components/layout'
import Head from 'next/head'
import { useRouter } from "next/router";

export default function Login() {
    const [text, setText] = useState('');
    const [password, setPassword] = useState('');
    const router = useRouter();

    function tryLogin(req, res) {
        const data = {
            userName: text,
            password: password
        }
        fetch('/api/login', {
            method: 'POST',
            body: JSON.stringify(data)
        })
            .then(response => response.json())
            .then(response => {
                if (response) {
                    // console.log(response);
                    localStorage.setItem('jwt', response);
                    router.push({
                        pathname: '/'
                    })
                }else{
                    alert('Wrong password!');
                    setText('');
                    setPassword('');
                }
            });
    }

    return (
            <Layout>
                <Head>
                    <title>Create Next App</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                </Head>

                <section class="text-gray-600 body-font relative">
                    <div class="container px-5 py-24 mx-auto">
                        <div class="flex flex-col text-center w-full mb-12">
                            <h1 class="sm:text-3xl text-2xl font-medium title-font mb-4 text-gray-900">학원톡톡</h1>
                            <p class="lg:w-2/3 mx-auto leading-relaxed text-base">시범테스트 중 입니다.</p>
                        </div>
                        <div class="lg:w-1/2 md:w-2/3 mx-auto">
                            <div class="flex flex-wrap -m-2">
                                <div class="p-2 w-1/2">
                                    <div class="relative">
                                        <label for="name" class="leading-7 text-sm text-gray-600">Name</label>
                                        <input type='text' value={text} onChange={(e) => setText(e.target.value)} class="w-full bg-gray-100 bg-opacity-50 rounded border border-gray-300 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out" />
                                    </div>
                                </div>
                                <div class="p-2 w-1/2">
                                    <div class="relative">
                                        <label for="email" class="leading-7 text-sm text-gray-600">Password</label>
                                        <input type='password' value={password} onChange={(e) => setPassword(e.target.value)} class="w-full bg-gray-100 bg-opacity-50 rounded border border-gray-300 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out" />
                                    </div>
                                </div>
                                <div class="p-2 w-full">
                                    <button onClick={tryLogin} class="flex mx-auto text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg">로그인</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>

                {/* <section className='relative w-screen h-[50vh]'>
                    <h1 className='absolute top-4 left-0 right-0 z-10 text-center leading-relaxed p-0 m-0 text-white text-[4rem]'>
                        차량 및 출결 연동
                        <br />
                        학생 관리 서비스
                    </h1>
                    <form className="flex items-center justify-center">
                        <span>아이디</span>
                        <input type='text' value={text} onChange={(e) => setText(e.target.value)}></input> <br />
                        <span>비밀번호</span>
                        <input type='password' value={password} onChange={(e) => setPassword(e.target.value)}></input>
                        <br />
                        <button onClick={tryLogin}>로그인</button>
                    </form>
                </section> */}
            </Layout>
            )
}